### PR TITLE
Java sample

### PR DESCRIPTION
**Pull request by chinhuang007**
Created a sample to show how the data model loader can be invoked from java. Also added types to the groovy method for java reflection to work.

### CODE REVIEW

**Review by tedhtchang — COMMENTED** [review]
@chinhuang007 Do we need instruction in the README on how to set this up in IDE or inside someone's java application?

**Comment by chinhuang007** [comment]
We can mention the sample in README. Probably don't need the complete instructions. The code is extremely straight forward.

**Comment by chinhuang007** [comment]
The README needs some work, still containing old name "JanusgraphGSONSchema". I suggest we do that after we merge all individual repositories under /github.com/ibm/janusgraph-utils

**Review by tedhtchang — APPROVED** [review]
LGTM

**Pull request merged**
